import { useEffect, useState } from "react";
import { api } from "../apiClient.js";

const defaultDraft = () => ({ title: "", summary: "", learningObjectives: [""], guideChallengeId: "computer-components", guideScript: [{ id: "cpu", title: "观察 CPU", instruction: "点击并观察 CPU 的位置。", action: { type: "highlightPart", partId: "cpu" }, completion: "acknowledge" }], assignmentOutline: { title: "", description: "" }, projectOutline: { title: "", description: "", milestones: [{ id: "proposal", title: "方案草稿", description: "说明分工和部件协作。" }] } });

export function TeacherCourseWorkbench({ classId, students = [] }) {
  const [drafts, setDrafts] = useState([]); const [projectReview, setProjectReview] = useState({ summary: {}, submissions: [] }); const [draft, setDraft] = useState(defaultDraft); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function refresh() { const [draftResult, reviewResult] = await Promise.all([api.teacherCourseDrafts(classId), api.projectSummary(classId)]); setDrafts(draftResult.drafts ?? []); setProjectReview(reviewResult); }
  useEffect(() => { refresh().catch((error) => setMessage(error.message)); }, [classId]);
  async function save() { try { setBusy(true); const result = await api.createCourseDraft(classId, draft); setDrafts([result.draft, ...drafts]); setDraft(defaultDraft()); setMessage("草稿已保存，发布前仍可审核和修改。"); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function generate() { try { setBusy(true); const result = await api.generateCourseDraft(classId, { title: draft.title, summary: draft.summary, learningObjectives: draft.learningObjectives }); setDrafts([result.draft, ...drafts]); setMessage(result.source === "ai" ? "已生成待审核草稿。" : "模型未配置，已生成可编辑的手动模板。"); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function publish(item) { if (!window.confirm(`发布“${item.title}”后课程定义将冻结，是否继续？`)) return; try { setBusy(true); await api.publishCourseDraft(item.id); await refresh(); setMessage("课程已发布，可以开始分组。"); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function review(submissionId, feedback) { try { setBusy(true); await api.reviewProjectSubmission(submissionId, feedback); await refresh(); setMessage("评价已发送，学生现在可以查看反馈。"); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  const summary = projectReview.summary ?? {};
  return <section className="teacher-studio-panel course-workbench"><div className="section-heading"><div><span className="eyebrow">课程工作台</span><h2>课程草稿与小组项目</h2><p>AI 建议和手动内容都必须经过教师审核后才能发布。</p></div></div>{message ? <p className="teacher-message">{message}</p> : null}<div className="course-workbench-grid"><form onSubmit={(event) => { event.preventDefault(); save(); }}><label>课程标题<input required value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><label>课程简介<textarea value={draft.summary} onChange={(event) => setDraft({ ...draft, summary: event.target.value })} /></label><label>学习目标<input required value={draft.learningObjectives[0]} onChange={(event) => setDraft({ ...draft, learningObjectives: [event.target.value] })} /></label><label>项目标题<input required value={draft.projectOutline.title} onChange={(event) => setDraft({ ...draft, projectOutline: { ...draft.projectOutline, title: event.target.value } })} /></label><label>项目说明<textarea required value={draft.projectOutline.description} onChange={(event) => setDraft({ ...draft, projectOutline: { ...draft.projectOutline, description: event.target.value } })} /></label><label>首个里程碑<input required value={draft.projectOutline.milestones[0].title} onChange={(event) => setDraft({ ...draft, projectOutline: { ...draft.projectOutline, milestones: [{ ...draft.projectOutline.milestones[0], title: event.target.value }] } })} /></label><div className="teacher-action-row"><button className="primary-button" disabled={busy} type="submit">保存课程草稿</button><button className="ghost-button" disabled={busy || !draft.title.trim() || !draft.learningObjectives[0].trim()} onClick={generate} type="button">生成建议模板</button></div></form><div><strong>已有课程</strong>{drafts.map((item) => <article className="course-draft-row" key={item.id}><strong>{item.title}</strong><small>{item.status === "published" ? "已发布" : "草稿"} · {item.projectOutline?.milestones?.length ?? 0} 个里程碑</small>{item.status === "draft" ? <button className="ghost-button" disabled={busy} onClick={() => publish(item)} type="button">审核并发布</button> : <TeamMaker draft={item} students={students} onMessage={setMessage} onCreated={refresh} />}</article>)}</div></div><ProjectReviewQueue summary={summary} submissions={projectReview.submissions ?? []} busy={busy} onReview={review} /></section>;
}

function TeamMaker({ draft, students, onMessage, onCreated }) { const [selected, setSelected] = useState(""); async function create() { try { await api.createProjectTeam(draft.id, { name: `第 ${Date.now().toString().slice(-3)} 组`, members: [{ studentId: Number(selected), role: "实验" }] }); await onCreated(); onMessage("小组已建立。"); } catch (error) { onMessage(error.message); } } return <span className="team-maker"><select value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">选择学生分组</option>{students.map((student) => <option key={student.id} value={student.id}>{student.displayName}</option>)}</select><button disabled={!selected} onClick={create} type="button">建立小组</button></span>; }

function ProjectReviewQueue({ summary, submissions, busy, onReview }) {
  const [feedback, setFeedback] = useState({});
  const pending = submissions.filter((submission) => submission.status === "submitted");
  return <section className="project-review-queue" aria-label="项目成果评价"><div className="section-heading"><div><span className="eyebrow">成果评价</span><h3>待评价里程碑</h3><p>已发布 {summary.publishedCourseCount ?? 0} 门课程，建立 {summary.teamCount ?? 0} 个小组，待评价 {pending.length} 份成果。</p></div></div>{pending.length === 0 ? <p className="empty-state">目前没有待评价的项目成果。</p> : <div className="project-review-list">{pending.map((submission) => <article className="project-review-item" key={submission.id}><header><strong>{submission.projectTitle} · {submission.milestoneTitle}</strong><small>{submission.teamName} / {submission.studentDisplayName} · {submission.teamRole}</small></header><p>{submission.reflection}</p>{submission.evidenceUrl ? <a href={submission.evidenceUrl} rel="noreferrer" target="_blank">查看成果链接</a> : null}<label>教师评价<textarea value={feedback[submission.id] ?? ""} onChange={(event) => setFeedback({ ...feedback, [submission.id]: event.target.value })} /></label><button className="primary-button" disabled={busy || !(feedback[submission.id] ?? "").trim()} onClick={() => onReview(submission.id, feedback[submission.id])} type="button">提交评价</button></article>)}</div>}</section>;
}
