import { useEffect, useState } from "react";
import { api } from "../apiClient.js";

const defaultDraft = () => ({ title: "", summary: "", learningObjectives: [""], guideChallengeId: "computer-components", guideScript: [{ id: "cpu", title: "观察 CPU", instruction: "点击并观察 CPU 的位置。", action: { type: "highlightPart", partId: "cpu" }, completion: "acknowledge" }], assignmentOutline: { title: "", description: "" }, projectOutline: { title: "", description: "", milestones: [{ id: "proposal", title: "方案草稿", description: "说明分工和部件协作。" }] } });

export function TeacherCourseWorkbench({ classId, students = [] }) {
  const [drafts, setDrafts] = useState([]); const [draft, setDraft] = useState(defaultDraft); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function refresh() { const result = await api.teacherCourseDrafts(classId); setDrafts(result.drafts ?? []); }
  useEffect(() => { refresh().catch((error) => setMessage(error.message)); }, [classId]);
  async function save() { try { setBusy(true); const result = await api.createCourseDraft(classId, draft); setDrafts([result.draft, ...drafts]); setDraft(defaultDraft()); setMessage("草稿已保存，发布前仍可审核和修改。"); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function generate() { try { setBusy(true); const result = await api.generateCourseDraft(classId, { title: draft.title, summary: draft.summary, learningObjectives: draft.learningObjectives }); setDrafts([result.draft, ...drafts]); setMessage(result.source === "ai" ? "已生成待审核草稿。" : "模型未配置，已生成可编辑的手动模板。"); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  async function publish(item) { if (!window.confirm(`发布“${item.title}”后课程定义将冻结，是否继续？`)) return; try { setBusy(true); await api.publishCourseDraft(item.id); await refresh(); setMessage("课程已发布，可以开始分组。"); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  return <section className="teacher-studio-panel course-workbench"><div className="section-heading"><div><span className="eyebrow">课程工作台</span><h2>课程草稿与小组项目</h2><p>AI 建议和手动内容都必须经过教师审核后才能发布。</p></div></div>{message ? <p className="teacher-message">{message}</p> : null}<div className="course-workbench-grid"><form onSubmit={(event) => { event.preventDefault(); save(); }}><label>课程标题<input required value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><label>课程简介<textarea value={draft.summary} onChange={(event) => setDraft({ ...draft, summary: event.target.value })} /></label><label>学习目标<input required value={draft.learningObjectives[0]} onChange={(event) => setDraft({ ...draft, learningObjectives: [event.target.value] })} /></label><label>项目标题<input required value={draft.projectOutline.title} onChange={(event) => setDraft({ ...draft, projectOutline: { ...draft.projectOutline, title: event.target.value } })} /></label><label>项目说明<textarea required value={draft.projectOutline.description} onChange={(event) => setDraft({ ...draft, projectOutline: { ...draft.projectOutline, description: event.target.value } })} /></label><label>首个里程碑<input required value={draft.projectOutline.milestones[0].title} onChange={(event) => setDraft({ ...draft, projectOutline: { ...draft.projectOutline, milestones: [{ ...draft.projectOutline.milestones[0], title: event.target.value }] } })} /></label><div className="teacher-action-row"><button className="primary-button" disabled={busy} type="submit">保存课程草稿</button><button className="ghost-button" disabled={busy || !draft.title.trim() || !draft.learningObjectives[0].trim()} onClick={generate} type="button">生成建议模板</button></div></form><div><strong>已有课程</strong>{drafts.map((item) => <article className="course-draft-row" key={item.id}><strong>{item.title}</strong><small>{item.status === "published" ? "已发布" : "草稿"} · {item.projectOutline?.milestones?.length ?? 0} 个里程碑</small>{item.status === "draft" ? <button className="ghost-button" disabled={busy} onClick={() => publish(item)} type="button">审核并发布</button> : <TeamMaker draft={item} students={students} onMessage={setMessage} />}</article>)}</div></div></section>;
}

function TeamMaker({ draft, students, onMessage }) { const [selected, setSelected] = useState(""); async function create() { try { await api.createProjectTeam(draft.id, { name: `第 ${Date.now().toString().slice(-3)} 组`, members: [{ studentId: Number(selected), role: "实验" }] }); onMessage("小组已建立。"); } catch (error) { onMessage(error.message); } } return <span className="team-maker"><select value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">选择学生分组</option>{students.map((student) => <option key={student.id} value={student.id}>{student.displayName}</option>)}</select><button disabled={!selected} onClick={create} type="button">建立小组</button></span>; }
